[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
grail_grove = "GrA1LdMTRsZPrLZLjbZbQ9Cx4XNbyL1bz7enprBkDv49"

[programs.localnet]
grail_grove = "GrA1LdMTRsZPrLZLjbZbQ9Cx4XNbyL1bz7enprBkDv49"

[programs.mainnet]
grail_grove = "GrA1LdMTRsZPrLZLjbZbQ9Cx4XNbyL1bz7enprBkDv49"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = ".keys/test-wallet.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
